/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uas;

import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Asus
 */
public class Uas extends javax.swing.JFrame {
//    double barang1=25000;
//    double barang2=50000;
//    double barang3=75000;
//    double totalhrgbrg1,totalhrgbrg2,totalhrgber3;
   // int jmlbrg1,jmlbrg2,jmlbrg3;
    /**
     * Creates new form Uas
     */
    public Uas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rbBarang1 = new javax.swing.JRadioButton();
        rbBarang2 = new javax.swing.JRadioButton();
        rbBarang3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        hargabarang1 = new javax.swing.JTextField();
        hargabarang2 = new javax.swing.JTextField();
        hargabarang3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jumlahbarang1 = new javax.swing.JTextField();
        jumlahbarang2 = new javax.swing.JTextField();
        jumlahbarang3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        diskonbarang1 = new javax.swing.JTextField();
        diskonbarang2 = new javax.swing.JTextField();
        diskonbarang3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        totalhargabarang1 = new javax.swing.JTextField();
        totalhargabarang2 = new javax.swing.JTextField();
        totalhargabarang3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        totalpembayaran = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        diskon5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        afterdiskon = new javax.swing.JTextField();
        total = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        bayar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        totalakhir = new javax.swing.JTextField();
        uangakhir = new javax.swing.JButton();
        hapussemua = new javax.swing.JButton();
        keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UAS Putri");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setText("Mini Kasir");

        rbBarang1.setText("Barang 1");
        rbBarang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBarang1ActionPerformed(evt);
            }
        });

        rbBarang2.setText("Barang 2");
        rbBarang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBarang2ActionPerformed(evt);
            }
        });

        rbBarang3.setText("Barang 3");
        rbBarang3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBarang3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Harga Barang");

        hargabarang1.setEditable(false);
        hargabarang1.setBackground(new java.awt.Color(204, 204, 255));

        hargabarang2.setEditable(false);
        hargabarang2.setBackground(new java.awt.Color(204, 204, 255));

        hargabarang3.setEditable(false);
        hargabarang3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Jumlah Barang");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Harga barang Diskon");

        diskonbarang1.setEditable(false);
        diskonbarang1.setBackground(new java.awt.Color(204, 204, 255));

        diskonbarang2.setEditable(false);
        diskonbarang2.setBackground(new java.awt.Color(204, 204, 255));

        diskonbarang3.setEditable(false);
        diskonbarang3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Total Harga");

        totalhargabarang1.setEditable(false);
        totalhargabarang1.setBackground(new java.awt.Color(204, 204, 255));

        totalhargabarang2.setEditable(false);
        totalhargabarang2.setBackground(new java.awt.Color(204, 204, 255));

        totalhargabarang3.setEditable(false);
        totalhargabarang3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Total Pembayaran");

        totalpembayaran.setEditable(false);
        totalpembayaran.setBackground(new java.awt.Color(204, 204, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Diskon 5% Jika Pembelian diatas 1.000.000");

        diskon5.setEditable(false);
        diskon5.setBackground(new java.awt.Color(204, 204, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Pembayaran Setelah Diskon");

        afterdiskon.setEditable(false);
        afterdiskon.setBackground(new java.awt.Color(204, 204, 255));

        total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total.setText("Total");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Bayar");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Uang Akhir");

        totalakhir.setEditable(false);
        totalakhir.setBackground(new java.awt.Color(204, 204, 255));

        uangakhir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        uangakhir.setText("Uang Akhir");
        uangakhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uangakhirActionPerformed(evt);
            }
        });

        hapussemua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hapussemua.setText("Hapus Semua");

        keluar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        keluar.setText("Keluar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(hapussemua)
                                        .addGap(342, 342, 342)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(30, 30, 30)))))
                                .addGap(107, 107, 107))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(493, 493, 493)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(diskonbarang1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(diskonbarang2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(diskonbarang3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(keluar)))
                                .addGap(106, 106, 106)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalhargabarang3)
                            .addComponent(totalhargabarang2)
                            .addComponent(totalhargabarang1)
                            .addComponent(totalpembayaran)
                            .addComponent(diskon5)
                            .addComponent(afterdiskon)
                            .addComponent(bayar)
                            .addComponent(totalakhir)
                            .addComponent(uangakhir, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(rbBarang2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbBarang1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(rbBarang3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(hargabarang2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hargabarang1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(hargabarang3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumlahbarang3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jumlahbarang1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahbarang2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(92, 92, 92)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbBarang1)
                    .addComponent(hargabarang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahbarang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diskonbarang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalhargabarang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbBarang2)
                            .addComponent(hargabarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahbarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jumlahbarang3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diskonbarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalhargabarang2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(hargabarang3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rbBarang3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(diskonbarang3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(totalhargabarang3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(diskon5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(afterdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(total)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(totalakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uangakhir)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(hapussemua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(keluar)
                        .addGap(39, 39, 39))))
        );

        pack();
    }// </editor-fold>                        

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
//        hargabarang1.setText(String.valueOf(barang1));
//        hargabarang2.setText(String.valueOf(barang2));
//        hargabarang2.setText(String.valueOf(barang3));
//        jmlbrg1=Integer.parseInt(jumlahbarang1.getText());
//        jmlbrg2=Integer.parseInt(jumlahbarang2.getText());
//        jmlbrg3=Integer.parseInt(jumlahbarang3.getText());
          double jmlbrg1=0, jmlbrg2=0, jmlbrg3=0,bayar=0,hrgbrg1=25000,hrgbrg2=50000,hrgbrg3=75000,diskon=0.01,totalhrg,hrgdiskon,diskonbrg1,diskonbrg2,diskonbrg3,totalhrgbrg1,totalhrgbrg2,totalhrgbrg3;
            try{
                jmlbrg1 = Double.parseDouble(jumlahbarang1.getText());
                jmlbrg2 = Double.parseDouble(jumlahbarang2.getText());
                jmlbrg3 = Double.parseDouble(jumlahbarang3.getText());
                //bayar = Double.parseDouble(totalpembayaran.getText());
            }catch(Exception err){
                showMessageDialog(null,"Inputan tidak boleh kosong");
            }
        
            if(jmlbrg1 >=50){
                totalhrg=hrgbrg1 * jmlbrg1 - diskon;
                hrgdiskon= hrgbrg1 *diskon;
                totalhargabarang1.setText(String.valueOf(totalhrg));
                diskonbarang1.setText(String.valueOf(hrgdiskon));
                
            }else{
                totalhrg=hrgbrg1 * jmlbrg1;
                totalhargabarang1.setText(String.valueOf(totalhrg));
            }
            
            if(jmlbrg2 >=50){
                totalhrg=hrgbrg2 * jmlbrg2 - diskon;
                hrgdiskon= hrgbrg2 *diskon;
                totalhargabarang2.setText(String.valueOf(totalhrg));
                diskonbarang2.setText(String.valueOf(hrgdiskon));
                
            }else{
                totalhrg=hrgbrg2 * jmlbrg2;
                totalhargabarang2.setText(String.valueOf(totalhrg));
            }
        
            if(jmlbrg3 >=50){
                totalhrg=hrgbrg3 * jmlbrg3 - diskon;
                hrgdiskon= hrgbrg3 *diskon;
                totalhargabarang3.setText(String.valueOf(totalhrg));
                diskonbarang3.setText(String.valueOf(hrgdiskon));
                
            }else{
                totalhrg=hrgbrg3 * jmlbrg3;
                totalhargabarang3.setText(String.valueOf(totalhrg));
            }
            
            double totalhrg1,totalhrg2,totalhrg3,totalbyr,tambahdiskon5persen=0,diskon5persen=0.05,hasil;
            totalhrg1=Double.parseDouble(totalhargabarang1.getText());
            totalhrg2=Double.parseDouble(totalhargabarang2.getText());
            totalhrg3=Double.parseDouble(totalhargabarang3.getText());
            totalbyr= totalhrg1+totalhrg2+totalhrg3;
            totalpembayaran.setText(String.valueOf(totalbyr));
            if(totalbyr >=1000000){
                tambahdiskon5persen=totalbyr*diskon5persen;
                diskon5.setText(String.valueOf(tambahdiskon5persen));
                hasil = totalbyr-tambahdiskon5persen;
                afterdiskon.setText(String.valueOf(hasil));
            }else{
                afterdiskon.setText(String.valueOf(totalpembayaran));
            }
            
            
    }                                     

    private void rbBarang1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        double hrgbrg1=25000;
        if(rbBarang1.isSelected()){
            hargabarang1.setText(String.valueOf(hrgbrg1));
        }else{
            hargabarang1.setText(String.valueOf("0"));
        }
    }                                         

    private void rbBarang2ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        double hrgbrg2=50000;
        if(rbBarang2.isSelected()){
            hargabarang2.setText(String.valueOf(hrgbrg2));
        }else{
            hargabarang2.setText(String.valueOf("0"));
        }
    }                                         

    private void rbBarang3ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        double hrgbrg3=75000;
        if(rbBarang3.isSelected()){
            hargabarang3.setText(String.valueOf(hrgbrg3));
        }else{
            hargabarang3.setText(String.valueOf("0"));
        }
    }                                         

    private void uangakhirActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        double hargasetelahdiskon,uangbayar,uangakhir;
        hargasetelahdiskon=Double.parseDouble(afterdiskon.getText());
        uangbayar=Double.parseDouble(bayar.getText());
        uangakhir=uangbayar-hargasetelahdiskon;
        if(uangakhir >=0){
            showMessageDialog(null, "uang kembalian : "+uangakhir);
        }else{
            showMessageDialog(null, "uang kurang : "+ uangakhir);
        }
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Uas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Uas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Uas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Uas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField afterdiskon;
    private javax.swing.JTextField bayar;
    private javax.swing.JTextField diskon5;
    private javax.swing.JTextField diskonbarang1;
    private javax.swing.JTextField diskonbarang2;
    private javax.swing.JTextField diskonbarang3;
    private javax.swing.JButton hapussemua;
    private javax.swing.JTextField hargabarang1;
    private javax.swing.JTextField hargabarang2;
    private javax.swing.JTextField hargabarang3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jumlahbarang1;
    private javax.swing.JTextField jumlahbarang2;
    private javax.swing.JTextField jumlahbarang3;
    private javax.swing.JButton keluar;
    private javax.swing.JRadioButton rbBarang1;
    private javax.swing.JRadioButton rbBarang2;
    private javax.swing.JRadioButton rbBarang3;
    private javax.swing.JButton total;
    private javax.swing.JTextField totalakhir;
    private javax.swing.JTextField totalhargabarang1;
    private javax.swing.JTextField totalhargabarang2;
    private javax.swing.JTextField totalhargabarang3;
    private javax.swing.JTextField totalpembayaran;
    private javax.swing.JButton uangakhir;
    // End of variables declaration                   
}
